apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: revproxy
  name: revproxy
spec:
  replicas: 2
  selector:
    matchLabels: 
      service: revproxy
  template:
    metadata:
      labels:
        service: revproxy
    spec:
      containers:
      - image: nlaarm2/revproxy
        name: revproxy
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"       
        ports:
        - containerPort: 8080
      restartPolicy: Always


