apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: apiproxy
  name: apiproxy
spec:
  replicas: 2
  selector:
    matchLabels: 
      service: apiproxy
  template:
    metadata:
      labels:
        service: apiproxy
    spec:
      containers:
      - image: nlaarm2/apiproxy
        name: apiproxy
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"       
        ports:
        - containerPort: 8080
      restartPolicy: Always


